name: Linux-Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  schedule: # run build job at 6am UTC every other week on Saturday
    - cron: '0 6 */14 * 6'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_FLAG: "\"-fprofile-arcs -ftest-coverage\""
  ACCOUNT: chengcli

jobs:
  unit-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false

      - name: create build directory
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j4

      - name: run unit tests
        working-directory: ${{github.workspace}}/build/tests
        run: ctest -j4
